services:
  # 1. MySQL Database Container
  db:
    image: mysql:8.0
    container_name: eventree_db
    restart: always
    environment:
      MYSQL_DATABASE: eventree
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: